#ifndef _CONFIG_H_
#define _CONFIG_H_
//#include "sdkconfig.h"

#define CONFIG_MQTT_MAX_HOST_LEN 64
#define CONFIG_MQTT_MAX_CLIENT_LEN 128
#define CONFIG_MQTT_MAX_USERNAME_LEN 128
#define CONFIG_MQTT_MAX_PASSWORD_LEN 512
#define CONFIG_MQTT_MAX_DEVICE_LEN 512
#define CONFIG_MQTT_MAX_PROJECT_ID_LEN 128
#endif